controller_manager:
  ros__parameters:
    update_rate: 100

    position_controller:
      type: position_controllers/JointGroupPositionController
    
    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

position_controller:
  ros__parameters:
    joints:
      - fr_wheel_rotate_joint
      - fl_wheel_rotate_joint
      - bl_wheel_rotate_joint
      - br_wheel_rotate_joint

velocity_controller:
  ros__parameters:
    joints:
      - fr_wheel_wheel_joint
      - fl_wheel_wheel_joint
      - bl_wheel_wheel_joint
      - br_wheel_wheel_joint

imu_sensor_broadcaster:
  ros__parameters:
    sensor_name: imu_sensor
    frame_id: imu_link
